version: '3'
services:
  delivery-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001' # Expose the app on port 3001
    env_file:
      - .env # Load environment variables from .env file
